// lib/storeTerms/seed.ts
// 既存運用に存在する規約の brand × category × title のマスター一覧。
// バリアント表記 (タイトル末尾の () / （）) を除いた基本タイトルで
// merge した結果を一覧画面に表示する。

export type SeedItem = { brand: string; category: string; title: string };

export const SEED_TERMS: SeedItem[] = [
  // FIT365
  { brand: "FIT365", category: "Web/APP入会", title: "特定商取引法に基づく表示" },
  { brand: "FIT365", category: "Web/APP入会", title: "あんしんサポート利用規約" },
  { brand: "FIT365", category: "Web/APP入会", title: "ご利用規約及び誓約書(契約別①)" },
  { brand: "FIT365", category: "Web/APP入会", title: "ご利用規約及び誓約書(契約別②)" },
  { brand: "FIT365", category: "Web/APP入会", title: "ご利用規約及び誓約書(契約別③)" },
  { brand: "FIT365", category: "Web/APP入会", title: "ご利用規約及び誓約書(契約別④)" },
  { brand: "FIT365", category: "Web/APP入会", title: "プライバシーポリシー" },
  { brand: "FIT365", category: "Web/APP入会", title: "ご入会にあたっての注意事項" },
  { brand: "FIT365", category: "Web/APP入会（法人）", title: "債務不履行の同意" },
  { brand: "FIT365", category: "デジタルチケット都度利用", title: "オプション都度利用規約" },
  { brand: "FIT365", category: "APP 同伴（同伴入退館）", title: "同伴者利用の規約確認" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "特定商取引法に基づく表示" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "あんしんサポート会員規約" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "ご利用規約及び誓約書(契約別①)" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "ご利用規約及び誓約書(契約別②)" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "ご利用規約及び誓約書(契約別③)" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "ご利用規約及び誓約書(契約別④)" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "プライバシーポリシー" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "退会手続き" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "ご入会にあたっての注意事項" },
  { brand: "FIT365", category: "KIOSK（桃）", title: "債務不履行の同意" },
  { brand: "FIT365", category: "KIOSK", title: "休会制度規約" },
  { brand: "FIT365", category: "KIOSK", title: "休会制度についてのご案内" },
  { brand: "FIT365", category: "KIOSK", title: "契約区分変更規約" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "特定商取引法に基づく表示" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "あんしんサポート会員規約" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "ご利用規約及び誓約書(契約別①)" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "ご利用規約及び誓約書(契約別②)" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "ご利用規約及び誓約書(契約別③)" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "ご利用規約及び誓約書(契約別④)" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "プライバシーポリシー" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "退会手続き" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "ご入会にあたっての注意事項" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "債務不履行の同意" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "休会制度規約" },
  { brand: "FIT365", category: "KIOSK（ワイド）", title: "休会制度についてのご案内" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "特定商取引法に基づく表示" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "あんしんサポート会員規約" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "ご利用規約及び誓約書(契約別①)" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "ご利用規約及び誓約書(契約別②)" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "ご利用規約及び誓約書(契約別③)" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "ご利用規約及び誓約書(契約別④)" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "プライバシーポリシー" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "退会手続き" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "ご入会にあたっての注意事項" },
  { brand: "FIT365", category: "KIOSK（黄）", title: "債務不履行の同意" },
  { brand: "FIT365", category: "1DayPass", title: "１Day Pass利用規約" },
  { brand: "FIT365", category: "各種お手続き", title: "特定商取引法に基づく表示" },
  { brand: "FIT365", category: "各種お手続き", title: "あんしんサポート会員規約" },
  { brand: "FIT365", category: "各種お手続き", title: "ご利用規約及び誓約書(契約別①)" },
  { brand: "FIT365", category: "各種お手続き", title: "ご利用規約及び誓約書(契約別②)" },
  { brand: "FIT365", category: "各種お手続き", title: "ご利用規約及び誓約書(契約別③)" },
  { brand: "FIT365", category: "各種お手続き", title: "ご利用規約及び誓約書(契約別④)" },
  { brand: "FIT365", category: "各種お手続き", title: "主契約変更手続き" },
  { brand: "FIT365", category: "各種お手続き", title: "プライバシーポリシー" },
  { brand: "FIT365", category: "各種お手続き", title: "ご入会にあたっての注意事項" },
  { brand: "FIT365", category: "各種お手続き", title: "退会手続き" },
  { brand: "FIT365", category: "各種お手続き", title: "休会制度規約" },
  { brand: "FIT365", category: "各種お手続き", title: "休会制度についてのご案内" },
  { brand: "FIT365", category: "KIOSK(QRコード読み取り)", title: "特定商取引法に基づく表示" },
  { brand: "FIT365", category: "KIOSK(QRコード読み取り)", title: "あんしんサポート会員規約" },
  { brand: "FIT365", category: "KIOSK(QRコード読み取り)", title: "ご利用規約及び誓約書(契約別①)" },
  { brand: "FIT365", category: "KIOSK(QRコード読み取り)", title: "ご利用規約及び誓約書(契約別②)" },
  { brand: "FIT365", category: "KIOSK(QRコード読み取り)", title: "ご利用規約及び誓約書(契約別③)" },
  { brand: "FIT365", category: "KIOSK(QRコード読み取り)", title: "ご利用規約及び誓約書(契約別④)" },
  { brand: "FIT365", category: "KIOSK(QRコード読み取り)", title: "プライバシーポリシー" },
  { brand: "FIT365", category: "KIOSK(QRコード読み取り)", title: "ご入会にあっての注意事項" },
  { brand: "FIT365", category: "MineFit向け1DayPass", title: "ストア利用の注意事項" },
  { brand: "FIT365", category: "レズミルズ契約（オプション）", title: "契約規約" },
  { brand: "FIT365", category: "レズミルズ解約（オプション）", title: "解約規約" },
  // JOYFIT
  { brand: "JOYFIT", category: "Web入会", title: "スポーツクラブJOYFITご利用規約" },
  { brand: "JOYFIT", category: "Web入会", title: "スポーツクラブJOYFIT個人情報取り扱いについて" },
  { brand: "JOYFIT", category: "Web入会", title: "JOYFITあんしんサポートについて" },
  { brand: "JOYFIT", category: "Web入会", title: "ご利用規約" },
  { brand: "JOYFIT", category: "Web入会", title: "特定商取引法に基づく表示" },
  { brand: "JOYFIT", category: "Web入会", title: "プライバシーポリシー" },
  { brand: "JOYFIT", category: "Web入会", title: "クレジットカードで簡単入会にて手続きのできる方、入会資格について(赤)" },
  { brand: "JOYFIT", category: "Web入会", title: "クレジットカードで簡単入会にて手続きのできる方、入会資格について(YOGA)" },
  { brand: "JOYFIT", category: "Web入会", title: "クレジットカードで簡単入会にて手続きのできる方、入会資格について(青)" },
  { brand: "JOYFIT", category: "Web入会", title: "クレジットカードで簡単入会にて手続きのできる方、入会資格について(EMS)" },
  { brand: "JOYFIT", category: "Web入会", title: "どこでもJOY同意書(赤)" },
  { brand: "JOYFIT", category: "Web入会", title: "どこでもJOY同意書(YOGA)" },
  { brand: "JOYFIT", category: "Web入会", title: "どこでもJOY同意書(青)" },
  { brand: "JOYFIT", category: "Web入会", title: "どこでもJOY同意書(EMS)" },
  { brand: "JOYFIT", category: "Web入会", title: "申し込み内容のご確認(赤)" },
  { brand: "JOYFIT", category: "Web入会", title: "申し込み内容のご確認(YOGA)" },
  { brand: "JOYFIT", category: "Web入会", title: "申し込み内容のご確認(青)" },
  { brand: "JOYFIT", category: "Web入会", title: "申し込み内容のご確認(EMS)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご利用時のお願い(赤①)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご利用時のお願い(赤②)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご利用時のお願い(赤Wide)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご利用時のお願い(赤Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご利用時のお願い(緑<yoga>)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご利用時のお願い(青Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご利用時のお願い(青)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "入会資格(赤①)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "入会資格(赤②)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "入会資格(赤Wide)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "入会資格(赤Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "入会資格(緑<yoga>)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "入会資格(青Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "入会資格(青)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "フリーウェイト・カーディオ機器使用に関しての注意事項(赤①)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "フリーウェイト・カーディオ機器使用に関しての注意事項(赤②)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "フリーウェイト・カーディオ機器使用に関しての注意事項(赤Wide)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "フリーウェイト・カーディオ機器使用に関しての注意事項(赤Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "フリーウェイト・カーディオ機器使用に関しての注意事項(緑<yoga>)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "フリーウェイト・カーディオ機器使用に関しての注意事項(青Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "フリーウェイト・カーディオ機器使用に関しての注意事項(青)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "JOYFIT安心サポートについて(赤①)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "JOYFIT安心サポートについて(赤②)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "JOYFIT安心サポートについて(赤Wide)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "JOYFIT安心サポートについて(赤Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "JOYFIT安心サポートについて(緑<yoga>)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "JOYFIT安心サポートについて(青Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "JOYFIT安心サポートについて(青)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "どこでもJOYについて(赤①)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "どこでもJOYについて(赤②)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "どこでもJOYについて(赤Wide)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "どこでもJOYについて(赤Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "どこでもJOYについて(緑<yoga>)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "どこでもJOYについて(青Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "どこでもJOYについて(青)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "プライバシーポリシー(赤①)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "プライバシーポリシー(赤②)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "プライバシーポリシー(赤Wide)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "プライバシーポリシー(赤Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "プライバシーポリシー(緑<yoga>)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "プライバシーポリシー(青Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "プライバシーポリシー(青)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご入会にあたっての注意事項(赤①)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご入会にあたっての注意事項(赤②)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご入会にあたっての注意事項(赤Wide)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご入会にあたっての注意事項(赤Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご入会にあたっての注意事項(緑<yoga>)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご入会にあたっての注意事項(青Size)" },
  { brand: "JOYFIT", category: "KIOSK入会", title: "ご入会にあたっての注意事項(青)" },
  { brand: "JOYFIT", category: "KIOSK休会", title: "休会申請はこちらから" },
  { brand: "JOYFIT", category: "Web休会", title: "休会のご案内" },
  { brand: "JOYFIT", category: "KIOSK退会", title: "退会申請はこちらから(赤①)" },
  { brand: "JOYFIT", category: "KIOSK退会", title: "退会申請はこちらから(赤②)" },
  { brand: "JOYFIT", category: "KIOSK退会", title: "退会申請はこちらから(赤Wide)" },
  { brand: "JOYFIT", category: "KIOSK退会", title: "退会申請はこちらから(赤Size)" },
  { brand: "JOYFIT", category: "KIOSK退会", title: "退会申請はこちらから(緑<yoga>)" },
  { brand: "JOYFIT", category: "KIOSK退会", title: "退会申請はこちらから(青Size)" },
  { brand: "JOYFIT", category: "KIOSK退会", title: "退会申請はこちらから(青)" },
  { brand: "JOYFIT", category: "OneTimePass", title: "利用規約" },
  { brand: "JOYFIT", category: "外部販売サイト WellnessPass(法人1DayPass)", title: "ご利用に際しての規約" },
  { brand: "JOYFIT", category: "いっしょにJOY", title: "注意事項(赤)" },
  { brand: "JOYFIT", category: "いっしょにJOY", title: "注意事項(青)" },
  { brand: "JOYFIT", category: "オンラインライブレッスン契約", title: "オンラインレッスン利用規約" },
  { brand: "JOYFIT", category: "オンラインライブレッスン解約", title: "オンラインレッスン利用規約" },
  { brand: "JOYFIT", category: "あすけんオンラインライブレッスン契約", title: "あすけんオンラインレッスン利用規約" },
  { brand: "JOYFIT", category: "MineFit向け1DayPass", title: "利用規約" },
  { brand: "JOYFIT", category: "レッスン（ヨガWEB予約）", title: "スタジオプログラムご予約のお客様へ" },
  // WellnessFrontier
  { brand: "WellnessFrontier", category: "Web入会", title: "ご入会される皆様へ" },
  { brand: "WellnessFrontier", category: "Web入会", title: "個人情報取り扱いについて（プライバシーポリシー）" },
  { brand: "WellnessFrontier", category: "Web入会", title: "ご入会にあたっての注意事項" },
  { brand: "WellnessFrontier", category: "Web入会", title: "入会資格" },
  { brand: "WellnessFrontier", category: "Web入会", title: "ご利用時のお願い" },
  { brand: "WellnessFrontier", category: "Web入会", title: "フリーウェイト・カーディオ機器使用に関しての注意事項" },
  { brand: "WellnessFrontier", category: "Web入会", title: "JOYFITあんしんサポートについて" },
  { brand: "WellnessFrontier", category: "Web入会", title: "営業システム・誓約書・休会制度規約" },
  { brand: "WellnessFrontier", category: "Web入会", title: "法人会員における入会に関する注意事項" },
  // エコジョイ
  { brand: "エコジョイ", category: "App入会", title: "ご入会される皆様へ" },
  { brand: "エコジョイ", category: "App入会", title: "プライバシーポリシー" },
  { brand: "エコジョイ", category: "App入会", title: "ご入会にあたっての注意事項" },
  { brand: "エコジョイ", category: "App入会", title: "入会資格" },
  { brand: "エコジョイ", category: "App入会", title: "ご利用時のお願い" },
  { brand: "エコジョイ", category: "App入会", title: "フリーウェイト・カーディオ機器使用に関しての注意事項" },
  { brand: "エコジョイ", category: "App入会", title: "どこでもJOY同意書" },
  { brand: "エコジョイ", category: "App入会", title: "あんしんサポート会員規約" },
  { brand: "エコジョイ", category: "App入会", title: "営業システム・誓約書・休会制度規約" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "あんしんサポートの解約に関するご注意" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "退会手続き" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "主契約変更手続き" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "ご入会される皆様へ" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "プライバシーポリシー" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "ご入会にあたっての注意事項" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "入会資格" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "ご利用時のお願い" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "フリーウェイト・カーディオ機器使用に関しての注意事項" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "どこでもJOY同意書" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "あんしんサポート会員規約" },
  { brand: "エコジョイ", category: "App各種お手続き", title: "営業システム・誓約書・休会制度規約" },
];

export const BRAND_CONFIG: Record<string, { color: string; bg: string }> = {
  FIT365: { color: "#ea580c", bg: "#fff7ed" },
  JOYFIT: { color: "#dc2626", bg: "#fef2f2" },
  WellnessFrontier: { color: "#7c3aed", bg: "#f5f3ff" },
  "エコジョイ": { color: "#059669", bg: "#ecfdf5" },
};

export const BRANDS = ["FIT365", "JOYFIT", "WellnessFrontier", "エコジョイ"];
